name: Manual Security Scan

on:
  workflow_dispatch:

jobs:
  manual-analysis:
    runs-on: ubuntu-latest
    name: STRIDE Threat Modeling
    
    steps:
      - name: Run STRIDE-GPT Analysis
        uses: mrwadams/stridegpt-action@main
        with:
          stride-api-key: ${{ secrets.STRIDE_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trigger-mode: manual