name: Automatic STRIDE GPT Threat Modeling

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      # Only run on code changes
      - '**.py'
      - '**.js'
      - '**.ts'
      - '**.java'
      - '**.go'
      - '**.rb'
      - '**.php'
      - '**.cs'
      - '**.swift'
      - '**.kt'

jobs:
  threat-modeling:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Run STRIDE GPT Threat Modeling
        uses: mrwadams/stridegpt-action@main
        with:
          stride-api-key: ${{ secrets.STRIDE_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trigger-mode: pr