name: STRIDE GPT Comment Trigger

on:
  issue_comment:
    types: [created]

jobs:
  threat-modeling:
    if: contains(github.event.comment.body, '@stride-gpt')
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: STRIDE GPT Threat Modeling
        uses: mrwadams/stridegpt-action@main
        with:
          stride-api-key: ${{ secrets.STRIDE_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          trigger-mode: comment
